### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by aldisonll** [AdobeDocs/uxp-photoshop-plugin-samples#63]
Is "drag and drop" possible to do?

**Comment by ErinFinnegan** [comment]
I don't think it's support yet, [based on this list](https://www.adobe.io/photoshop/uxp/guides/uxp_guide/unsupported/#web-features). The [Photoshop roadmap is here](https://trello.com/b/Qag1BazI/photoshop-extensibility-roadmap), but I didn't find it there... although it seemed like it was [on the way last spring](https://forums.creativeclouddeveloper.com/t/create-new-folder-without-dialog-using-uxp/2751/2?u=erin_finnegan)... perhaps double-check in those forums.

**Comment by jardicc** [comment]
You can do that within your panel for sure. Other targets are unknown to me. I mean you can use events like dragStart, dragEnd, dragOver, dragLeave... so maybe with dragStart and dragOver (panel edges) could assume dragging into currently active document... but that solution would be a bit sketchy :-D And there wouldn't be reason for drag at all since onClick could do the same.
