### ISSUE TITLE
Add Webpack configuration for Production Build

### ISSUE THREAD

**Issue by ThisIsMrAli** [AdobeDocs/uxp-photoshop-plugin-samples#65]
### There is no configuration for production build of Webpack.
As an Example, After i added Production configuration for [UI React Starter](https://github.com/AdobeDocs/uxp-photoshop-plugin-samples/tree/main/ui-react-starter) the bundle Size reduced from 2.6 MB to 155KB and in another example reduced from 22MB to 1.5MB.
It is Essential to have such that configuration for better performance and lower bundle Size.

![image](https://user-images.githubusercontent.com/31847887/148908024-814d9e7c-49c5-45be-b3a0-4dbbc4ab21c4.png)
![image](https://user-images.githubusercontent.com/31847887/148907913-2f062e9b-d7c7-495d-b8c9-43cf20893704.png)

### Instruction to Add Configuration

1.  Add a  new script in package.json:`"build:prod": "webpack --mode production"`
2. Open webpack.config.js, change the structure from `module.exports = {}` to `module.exports = (env, options) => ({})`
3. If there is a devtool specified in webpack.config.js, edit that like this: `devtool: options.mode === 'production' ? 'none' : 'cheap-eval-source-map'`

Thanks for your wonderful works on UXP platfrom, I already added these configuration for Production build, If you allow me i can make a pull request.

**Comment by ThisIsMrAli** [comment]
@pklaschka i've already fixed this problem, but i cant push the branch to make pull request. can you insist me with that?

Thanks.

**Comment by pklaschka** [comment]
Hi there!

Sorry about the late response!

Since you're (presumably) not working at Adobe, you'll have to fork this repository in order to make changes. Then, you can create a pull request.

To do this, you can click the fork button on the repository's homepage. Then, this creates a repository under your username, where you can make the changes. Last but not least, you can then open a pull request from your fork back to this repository.

I hope this helps,
Please let me know if you have any questions.
Pablo

**Comment by ThisIsMrAli** [comment]
Hi @pklaschka 
Thanks for letting me know. I've already opened a pull request. can you take a look? 
https://github.com/AdobeDocs/uxp-photoshop-plugin-samples/pull/75

Thanks,
Ali

**Comment by pklaschka** [comment]
Closed by #75
